### ISSUE TITLE
Research MIDI from iOS to OS X/Ableton

### ISSUE THREAD

**Issue by tmatthias29** [JLT-G-2016/MIDIBINZ#9]

**Comment by tmatthias29** [comment]
Notes:

http://stackoverflow.com/questions/26494434/using-midipacketlist-in-swift
http://stackoverflow.com/questions/27416435/send-and-receive-midi-with-swift-and-coremidi

**Comment by tmatthias29** [comment]
http://www.rockhoppertech.com/blog/swift-3-core-midi/

**Comment by gabelam** [comment]
Gabe will be doing coreMIDI chapter in iOS book.

**Comment by cannonball6** [comment]
Found interesting build.  Will research more laters...
https://github.com/genedelisa/Swift2MIDI
